name: Hello CI

on: [push]

env:
  APP_NAME: my-first-ci
  ENVIRONMENT: dev

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: |
          echo "App = $APP_NAME"
          echo "Env = $ENVIRONMENT"
