name: Hello CI

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v4

      - name: list repository files
      - run: ls -la

      - name: print working directory
      - run: pwd
      
